version: '3'

services: 
  students-pickup:
    build:
      dockerfile: Dockerfile
      context: ../.
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy: 
        condition: on-failure
