version: '3'

services: 
  students-pickup:
    image: christianseki/students-pickup:latest
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy: 
        condition: on-failure
    networks:
      - public
networks:
  public:
    external:
      name: public