- name: copy the stack template to the remote host
  copy:
    src: "docker-compose.yaml"
    dest: "/opt/docker-compose.yaml"

- name: Deploy stack from a compose file
  docker_stack:
    state: present
    name: students-pickup
    compose:
      - /opt/docker-compose.yaml
  environment:
    QUEUE: ${QUEUE}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}