name: Deploy App
on:
  push:
    branches: [master]

jobs:
  donwload-config:
    name: Download swarm cluster config
    runs-on: ubuntu-latest
    steps:  
    - name: download swarm hosts config 
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        source: s3://swarm-machines-tf/hosts
        destination: ./
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: sa-east-1

    - name: Upload hosts config
      uses: actions/upload-artifact@v3
      with:
        name: hosts
        path: hosts

  deploy-swarm:
    name: Deploy to Swarm Cluster
    needs: donwload-config
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download swarm hosts config
      uses: actions/download-artifact@v3
      with:
        name: hosts

    - name: generate secret cert for ansible
      run: |
          echo ${{ secrets.SWARM_MACHINES_KEY }} | base64 -d > ansible/swarm-machines.pem
          chmod 400 ansible/swarm-machines.pem
      shell: bash

    - name: deploy to stack with run ansible playbook
      run: mv hosts ansible && cd ansible && ansible-playbook main.yaml
