name: Deploy AWS Resources
on:
  push:
    branches: [master]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_sns_update_responsible_topic_arn: ${{ secrets.TF_VAR_sns_update_responsible_topic_arn }}

jobs:
  terraform-plan:
    name: Plan Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terraform init
        run: cd terraform && terraform init -input=false

      - name: Terraform validation
        run: cd terraform && terraform validate

      - name: Terraform plan
        run: cd terraform && terraform plan -input=false  

  deploy-terraform:
    name: Apply Terraform
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment:
      name: deploy
      url: ${{ steps.step_id.outputs.url_output }}
    steps:
    - uses: actions/checkout@v1

    - name: Terraform init
      run: cd terraform && terraform init -input=false

    - name: Terraform validation
      run: cd terraform && terraform validate

    - name: Terraform apply
      run: cd terraform && terraform apply -auto-approve -input=false      